August-ToyProject/PDF-Quiz

.gitignore
BE/fastapi/quiz-application/.gitignore
BE/fastapi/quiz-application/requirements.txt
BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
BE/fastapi/quiz-application/src/app/app.py
BE/fastapi/quiz-application/src/app/urls.py
BE/fastapi/quiz-application/src/common/conf/settings.py
BE/fastapi/quiz-application/src/packages/decorators/logging_decorator.py
BE/fastapi/quiz-application/src/packages/decorators/processing_time.py

> close #10 
> Fast APi 초기 설정 및 테스트
> 
> 
> 
>

feat[#10] : Fastapi 기본설정 및 라우트 확인 완료

---

BE/spring/quiz-application/build.gradle
BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/swagger/SwaggerConfig.java
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/MemberResponse.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java

---
title: ''
labels: ''
assignees: ''
---
> 
>  이메일 인증은 아직 진행하지 않았고 간단히 이메일, 비밀번호만 입력받아 회원가입하고 DB 저장시 비밀번호는 암호화되어 저장
>  테스트 코드는 후에 작성 예정이고, intellij http test 기능을 통해 Api 동작여부 확인
>  비밀번호 및 이메일 형식 검증은 작업 예정
> 
> 
> 
>

feat[#15]:  기본적인 회원 가입

---

FE/pdf_quiz/package-lock.json
FE/pdf_quiz/package.json
FE/pdf_quiz/src/App.tsx
FE/pdf_quiz/src/pages/Login.tsx
FE/pdf_quiz/src/pages/SignUp.tsx

---
title: ''
labels: ''
assignees: ''
---
> 
> 
> 
> 
> 
>

Feature/#19 fe 로그인

---

BE/spring/quiz-application/build.gradle
BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/BusinessException.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/BusinessExceptionResponse.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ErrorCode.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ExceptionHandlerController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/DuplicateEmailException.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java

---
title: ''
labels: ''
assignees: ''
---
>  #22
> 회원가입시 필드 검증 및 에러 처리
> 
> 
> 
>

feat[#22]: 회원가입 검증 기능

---

BE/fastapi/quiz-application/requirements.txt
BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
BE/fastapi/quiz-application/src/app/api/file_service/helpers/file_service.py
BE/fastapi/quiz-application/src/app/api/file_service/service/file_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/shema/quiz_request.py
BE/fastapi/quiz-application/src/common/conf/settings.py

---
title: ''
labels: ''
assignees: ''
---
> close #25 
> PDF 업로드 후 퀴즈 생성
> 
> 
> 
>

feat[#25] : Fast API 퀴즈 생성 프롬프트 추가 및 테스트 완료

---

BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomAuthenticationFilter.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomUserDetailsService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/handler/LoginFailureHandler.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/handler/LoginSuccessHandler.java
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Role.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/LoginRequestDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java

---
title: ''
labels: ''
assignees: ''
---
> #30
> 프론트와 통신을 위한 CORS 처리
> 기본 인증
> 
> 
> 
>

feat[#30]:  로그인 기능

---

FE/pdf_quiz/.vite/deps_temp_abeeb767/package.json
FE/pdf_quiz/src/App.tsx
FE/pdf_quiz/src/components/Modal.tsx
FE/pdf_quiz/src/components/Upload.tsx
FE/pdf_quiz/src/pages/Login.tsx
FE/pdf_quiz/src/pages/MyPage.tsx
FE/pdf_quiz/src/pages/SignUp.tsx

---
title: ''
labels: ''
assignees: ''
---
> 
> 마이페이지 기본 레이아웃 구현
> 공용 모달 컴포넌트 폴더 생성 및 모달 구현
> 회원가입 페이지 서버 통신 테스트 완료
> 
> 
> 
>

feat[#26]: 마이페이지 레이아웃 구성 및 공용 모달 구현

---

FE/pdf_quiz/src/Hooks/OMR.tsx

---
title: ''
labels: ''
assignees: ''
---
> #45 
> OMR 화면에 그리는 로직 구현
- Todo: OMR 선택시 문제 및 사용자의 답안 기록 및 고른 답색칠하기
> 
> 
> 
>

feat[#45]: OMR UI 렌더링 구현

---

FE/pdf_quiz/src/Modal/Submit.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

---
title: ''
labels: ''
assignees: ''
---
> #46 
> 
> 
> 
> 
>

feat[#46]: 퀴즈 페이지 제출 모달 구현

---

FE/pdf_quiz/src/Hooks/OMR.tsx
FE/pdf_quiz/src/Hooks/userAnswers.ts

---
title: ''
labels: ''
assignees: ''
---
> #50 
> OMR 기능 구현
> 
> 
> 
>

feat[#50] OMR 기능 구현

---

FE/pdf_quiz/src/pages/MyPage copy.tsx
FE/pdf_quiz/src/pages/SignUp.tsx

---
title: ''
labels: ''
assignees: ''
---
> #44
> 회원가입 반응형 적용 (x) -> 반응형 영향 안 받음
> 마이페이지 반응형 적용 (o) -> 일반 화면 및 창모드 반응형 적용
> 
> 
> 
>

feat[#44] : 마이페이지 반응형 적용

---

BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
BE/fastapi/quiz-application/src/app/api/file_service/helpers/file_service.py
BE/fastapi/quiz-application/src/app/api/file_service/service/file_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/shema/quiz_request.py

---
title: ''
labels: ''
assignees: ''
---
close #53 
> 프롬프트 엔지니어링
> 프롬프트 처리
> 
> 
> 
>

refactor[#53]:프롬프트 재적용

---

BE/fastapi/quiz-application/docker-compose.yml
BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py

---
title: ''
labels: ''
assignees: ''
---
> close #47 
> python - kafka 적용
> 
> 
> 
>

feat[#47]: python-kafka 적용 및 테스트 완료

---

BE/fastapi/quiz-application/.gitignore
BE/fastapi/quiz-application/requirements.txt

---
title: ''
labels: ''
assignees: ''
---
> close #59 
> fast api 의존성 추가
> 
> 
> 
>

refactor[#59]: 의존성 추가

---

FE/pdf_quiz/src/App.tsx
FE/pdf_quiz/src/Hooks/UseQuery.tsx
FE/pdf_quiz/src/pages/FindAccount.tsx
FE/pdf_quiz/src/pages/Login.tsx

---
title: ''
labels: ''
assignees: ''
---
> #65 
> 
Todo: 서버에서 사용자 정보 가져오는 부분은 추가 개발 필요!
> 
- []  단위 테스트를 추가하거나 업데이트했습니다.
> 
> 
>

Feature/#65 fe 아이디비밀번호 찾기

---

BE/spring/quiz-application/build.gradle
BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/TokenProvider.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/MemberResponse.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ErrorCode.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/PasswordMismatchException.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java

---
title: ''
labels: ''
assignees: ''
---
> 64
> 
> 
> 
> 
>

feat[#64]: 로그아웃

---

FE/pdf_quiz/src/App.css

---
title: 'refactor[#68] : 불필요 css 코드 제거'
labels: ''
assignees: ''
---
> #68 
> 
ㅋ꙼̈
> 
> 
> 
>

refactor[#68] : 불필요 css 코드 제거

---

BE/spring/quiz-application/src/main/java/com/quizapplication/controller/pdf/PdfUploadController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/pdf/Pdf.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/PdfUploadResponse.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ExceptionHandlerController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/pdf/PdfRepository.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadServiceImpl.java

---
title: ''
labels: ''
assignees: ''
---
> #70 
>  pdf 관련 DB 테이블 생성 및 파일 업로드 구현
> 
> 
> 
>

feat[#70]: PDF 업로드 구현

---

BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumer.java
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/notification/NotificationController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/pdf/PdfUploadController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/pdf/Pdf.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/quiz/Quiz.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/PythonQuizRequest.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/QuizGenerateRequest.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/quiz/QuizOption.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/quiz/QuizResponse.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/EmitterRepository.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/NotificationService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadServiceImpl.java

---
title: ''
labels: ''
assignees: ''
---
#79 
> 
> 
> 
>

feat[#79] SSE 설정

---

BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/shema/quiz_request.py

---
title: ''
labels: ''
assignees: ''
---
> close #80 
> 요청 바디 및 반환 값 변경
> 
> 
> 
>

refactor[#80]: 퀴즈 생성 반환값 추가

---

FE/pdf_quiz/src/App.tsx
FE/pdf_quiz/src/Hooks/useSSE.tsx
FE/pdf_quiz/src/pages/SSEPage.tsx

---
title: ''
labels: ''
assignees: ''
---
> #82 
> 
> 
- 테스트 필요
> 
> 
>

Feature/#82 fe sse 설정

---

FE/pdf_quiz/src/Hooks/OMR.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

> #88 
> 
(1) 1024px 이하로 줄일 경우
(2) 860px 이하로 줄일 경우
> 
> 
> 
>

feat[#88]: 퀴즈 페이지 반응형 적용

---

BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java

> #100 
> 스웨거 인증 제외
> 
> 
> 
>

feat[#100]: 스웨거 인증 제외

---

FE/pdf_quiz/src/App.css
FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/Quiz.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

> #97 
> 퀴즈 페이지 페이지 네이션 적용
Todo: 현재는 가짜 데이터 fetch 해서 보여주는 중, clientSSE 테스트 시 같이 봐야하
> 
> 
> 
>

Feature/#97 페이지네이션

---

FE/pdf_quiz/package-lock.json
FE/pdf_quiz/package.json
FE/pdf_quiz/src/pages/Login.tsx
FE/pdf_quiz/src/pages/SignUp.tsx

> close #103 
> 회원가입 api 테스트 완료 -> 로그인 및 로그아웃은 확인 후 재진행 예정
> 
> 
> 
>

feat[#103] : 회원가입 api 테스트 완료

---

BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomAuthenticationFilter.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomUserDetailsService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/LoginRequestDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java

> #107 
> 로그인 방식 변경
> 
> 
> 
>

feat[#107]: 로그인 방식 변경

---

FE/pdf_quiz/src/Modal/findID.tsx
FE/pdf_quiz/src/pages/FindAccount.tsx

> #105 
> 아이디 찾기 기능
> 
> 
> 
>

Feature/#105 아이디 찾기 기능 완성

---

BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java

> #111 
>  인증 /인가 헤더 설정
> 
> 
> 
>

feat[#111]: 인증/인가 헤더 설정

---

FE/pdf_quiz/src/pages/Login.tsx

feat[#113]: 로그인 요청데이터 변경 및 액세스 토큰 저장 확인 테스트

---

BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/EditUserInfoDto.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java

> #116 
> 유저 정보 수정 api 작성
> 
> 
> 
>

feat[#116]: 유저정보 수정

---

FE/pdf_quiz/src/Modal/Upload.tsx

> #117 
> PDF 업로드 테스트
> 
> 
> 
>

feat[#117]:PDF 업로드 테스트 완료

---

FE/pdf_quiz/index.html
FE/pdf_quiz/src/api/ApiClient.tsx
FE/pdf_quiz/src/api/ApiFolder.tsx
FE/pdf_quiz/src/api/ApiQuiz.tsx
FE/pdf_quiz/src/api/ApiUser.tsx
FE/pdf_quiz/src/pages/MyPage.tsx
FE/pdf_quiz/src/pages/SignUp.tsx
FE/pdf_quiz/vite.config.ts
package-lock.json

> #119 
> 회원가입 -> 로그인 -> 로그아웃 api통신 모두 완료
> 
> 
> 
>

feat[#119]: 회원가입 -> 로그인 -> 로그아웃 모두 api테스트 완료

---

FE/pdf_quiz/src/Hooks/useSSE.tsx
FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

Feature/#110 입력값 상태관리

---

BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
BE/spring/quiz-application/src/main/java/com/quizapplication/domain/folder/Folder.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/folder/FolderCreateRequest.java
BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/FolderResponse.java
BE/spring/quiz-application/src/main/java/com/quizapplication/repository/folder/FolderRepository.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java

> #125 
> 폴더 관련 API 작성
> 
> 
> 
>

feat[#125]  폴더 관련 API 작성

---

FE/pdf_quiz/package-lock.json
FE/pdf_quiz/package.json
FE/pdf_quiz/src/App.tsx
FE/pdf_quiz/src/api/ApiClient.tsx
FE/pdf_quiz/src/api/ApiUser.tsx
FE/pdf_quiz/src/pages/InfoPage.tsx
FE/pdf_quiz/src/pages/Login.tsx
FE/pdf_quiz/src/pages/MyPage.tsx

> #122 
> 내정보 페이지 정보확인 및 수정 구현 및 API통신 테스트 완료
> 
> 
> 
>

feat[#122]: 내정보 페이지 구현 및 API테스트 완료, Login실패 처리

---

BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py

> close #94 
> 클로드 api 변경 -> 중복 문제 해결 실패
> 
> 
> 
>

refactoring[#94] : 클로드 적용 - 다시해야함

---

FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/QuizData.tsx
FE/pdf_quiz/vite.config.ts

Feature/#128 퀴즈 불러오기

---

FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

> #132 
> 퀴즈 불러오기 api 테스트 완료
> 
> 
> 
>

Feature/#132 퀴즈 불러오기

---

FE/pdf_quiz/.gitignore
FE/pdf_quiz/src/Hooks/OMR.tsx
FE/pdf_quiz/src/Hooks/Timer.tsx
FE/pdf_quiz/src/context/QuizContext.tsx
FE/pdf_quiz/src/pages/MyPage.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

Feature/#135 사용자값 상태관리

---

FE/pdf_quiz/src/Hooks/OMR.tsx
FE/pdf_quiz/src/Hooks/userAnswers.ts
FE/pdf_quiz/src/Modal/Submit.tsx
FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/Quiz.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

Feature/#144 정답값 전달

---

FE/pdf_quiz/src/Hooks/useSSE.tsx
FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/api/ApiQuiz.tsx
FE/pdf_quiz/src/components/PostIt.tsx
FE/pdf_quiz/src/event-source-polyfill.d.ts
FE/pdf_quiz/src/pages/Answer.tsx
FE/pdf_quiz/src/pages/InfoPage.tsx
FE/pdf_quiz/src/pages/MyPage.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

> close #151 
> npm run build 타입스크립트 에러 수정
> 
> 
> 
>

fix[#151] : npm build 에러 수정

---

FE/pdf_quiz/src/Modal/Upload.tsx

> #161 
> 로딩 스피너 추가
> 
> 
> 
>

feat: 로딩 스피너 추가

---

FE/pdf_quiz/src/Modal/agreementModal.tsx
FE/pdf_quiz/src/pages/SignUp.tsx

> #166 
> 회원가입시 개인정보동의 후 가입 완료
> 
> 
> 
>

feat[#166]: 개인정보수집동의추가

---

FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/Modal/answerSave.tsx
FE/pdf_quiz/src/context/QuizContext.tsx
FE/pdf_quiz/src/pages/Answer.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

Feat/#172 시험지이름커스텀

---

BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py

> #162 
> 키워드 중복 문제 수정
> 
> 
> 
>

refactor[#162] : 프롬프트 2차 수정

---

FE/pdf_quiz/src/Hooks/OMR.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

design: 퀴즈 페이지 디자인 수정

---

FE/pdf_quiz/src/pages/InfoPage.tsx

feat: 로고에 마이페이지 네비게이션 추가

---

FE/pdf_quiz/src/App.tsx
FE/pdf_quiz/src/api/ApiQuiz.tsx
FE/pdf_quiz/src/components/folderList.tsx
FE/pdf_quiz/src/pages/Answer.tsx
FE/pdf_quiz/src/pages/ListAnswer.tsx
FE/pdf_quiz/src/pages/MyPage.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

feature[#170]: 시험결과확인API통신완료

---

FE/pdf_quiz/src/Hooks/OMR.tsx
FE/pdf_quiz/src/Hooks/userAnswers.ts
FE/pdf_quiz/src/Modal/Submit.tsx
FE/pdf_quiz/src/context/QuizContext.tsx
FE/pdf_quiz/src/pages/Answer.tsx
FE/pdf_quiz/src/pages/Quiz.tsx

Fix/#189 omr상태관리 수정

---

FE/pdf_quiz/src/components/folderList.tsx
FE/pdf_quiz/src/pages/ListAnswer.tsx
FE/pdf_quiz/src/pages/MyPage.tsx

feat[#191]: PDF Upload버튼 반응형 시 적용, 버튼 커서 숨김

---

FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/Login.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

>  close #201 
>  http -> https 
> 
> 
> 
>

refacor[#201] : http -> https

---

BE/spring/quiz-application/Dockerfile

> #206 
> docker file 작성
> 
> 
> 
>

feat[#206] docker파일 작성

---

BE/spring/quiz-application/src/main/java/com/quizapplication/config/async/AsyncService.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java

feat[#206]: SSE 변경

---

.github/workflows/react_git_action.yaml
FE/pdf_quiz/src/Hooks/Timer.tsx
FE/pdf_quiz/src/context/QuizContext.tsx
FE/pdf_quiz/src/pages/QuizData.tsx

> #210 
> 타이머 시작 타이밍 수정
> 
> 
> 
>

Fix/#210 타이머 타이밍수정(사용자 피드백)

---

BE/spring/quiz-application/build.gradle
BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ErrorCode.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/DuplicateEmailException.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/MemberErrorCode.java
BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/MemberException.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java

feat[#206]: 도커

---

FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/TempPage.tsx
FE/pdf_quiz/tailwind.config.js

> 
> 에러메세지 모달 추가, 알림 스낵바 추가, 업로드모달 디자인 수정
> 
> 
> 
>

feature/업로드 이미지 수정 및 에러메세지 추가

---

FE/pdf_quiz/src/Modal/Upload.tsx
FE/pdf_quiz/src/pages/TempPage.tsx

fix/폴더 좌측 정렬 수정

---

BE/spring/quiz-application/http/member.http
BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java
BE/spring/quiz-application/src/test/java/com/quizapplication/member/MemberServiceTest.java

Feature/#227 be 오답노트

---

BE/spring/quiz-application/src/main/java/com/quizapplication/config/oauth/handler/OAuth2LoginSuccessHandler.java

feat: redirect

---

FE/pdf_quiz/src/Modal/actionModal.tsx
FE/pdf_quiz/src/pages/MyPage.tsx
FE/pdf_quiz/src/pages/TempPage.tsx

> 
> 이메일인증 디버깅
> 폰트 수정
> 
> 
> 
>

feature/이메일인증디버깅 및 폰트 수정
